version: "3"

services:
  gitea-db:
    image: postgres:14
    container_name: gitea-db
    restart: always
    environment:
      POSTGRES_USER: gitea
      POSTGRES_PASSWORD: gitea_pass
      POSTGRES_DB: gitea
    volumes:
      - gitea_db:/var/lib/postgresql/data
    networks:
      - gitea_net

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    environment:
      USER_UID: 1000
      USER_GID: 1000
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: gitea-db:5432
      GITEA__database__NAME: gitea
      GITEA__database__USER: gitea
      GITEA__database__PASSWD: gitea_pass
    volumes:
      - gitea_data:/data
    ports:
      - "3000:3000" # 웹 UI 접속 포트
      - "2222:22" # SSH 접속 포트
    networks:
      - gitea_net

volumes:
  gitea_db:
  gitea_data:

networks:
  gitea_net:
